#fake-api:
#  url: https://fakestoreapi.com
#
#spring:
#  cloud:
#    loadbalancer:
#      ribbon:
#        enable: true
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/fake-api?createDatabaseIfNotExist=TRUE&serverTimezone=UTC
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#      hibernate:
#        ddl-auto: update
#        properties:
#          hibernate:
#            package-to-scan: com.hdlg9la.feignclientjavaapi.infrastructure.entity
#            format_sql: true
#            dialect: org.hibernate.dialect.PostgreSQLDialect
#      show-sql: true
#      database-platform: org.hibernate.dialect.MySQLDialect
#
#server:
#  port: 8181

fake-api:
  url: https://fakestoreapi.com

spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/fake-api?createDatabaseIfNotExist=TRUE&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          package-to-scan: com.hdlg9la.feignclientjavaapi.infrastructure.entity
          format_sql: true
          dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8181

